apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: 192.168.1.183:6161/helloworld:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: helloworld
spec:
  selector:
    app: helloworld
  ports:
  - port: 80
    nodePort: 30009
    targetPort: 7000
    protocol: TCP
  type: NodePort