Vagrant.configure("2") do |config|

  config.vm.define "buildagent" do |buildagent|
    buildagent.vm.box = "ubuntu/focal64"
	config.vm.box_download_insecure=true
	config.vm.boot_timeout
    config.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller"
	buildagent.vm.provider "virtualbox" do |vb|
     vb.memory = "6000"
	 vb.name = "buildagent"
	 vb.cpus = 2
   end
   buildagent.vm.provision "shell", inline: <<-SHELL
   
   sudo hostnamectl set-hostname buildagent
   #installjenkins
   sudo wget -O - https://raw.githubusercontent.com/onuromertunc/helloworld/main/IaC/jenkinsinstall.sh | bash
   #installdocker
   sudo wget -O - https://raw.githubusercontent.com/onuromertunc/helloworld/main/IaC/dockerinstall.sh | bash
   
   SHELL
  end

#k8smaster
  config.vm.define "k8smaster" do |k8smaster|
    k8smaster.vm.box = "ubuntu/focal64"
	config.vm.box_download_insecure=true
	config.vm.boot_timeout
    config.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller"
	k8smaster.vm.provider "virtualbox" do |vb|
     vb.memory = "3000"
	 vb.cpus = 2
   end
   k8smaster.vm.provision "shell", inline: <<-SHELL
   sudo apt-get update
  
   
   SHELL
  end
#k8sworker
  config.vm.define "k8sworker" do |k8sworker|
    k8sworker.vm.box = "ubuntu/focal64"
	config.vm.box_download_insecure=true
	config.vm.boot_timeout
    config.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller"
	k8sworker.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
	 vb.cpus = 2
   end
   k8sworker.vm.provision "shell", inline: <<-SHELL
   sudo apt-get update
  
   
   SHELL
  end
 
end