Vagrant.configure("2") do |config|

  config.vm.define "buildagent" do |buildagent|
    buildagent.vm.box = "ubuntu/focal64"
	config.vm.box_download_insecure=true
	config.vm.boot_timeout
    config.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller"
	buildagent.vm.provider "virtualbox" do |vb|
     vb.memory = "6000"
	 vb.name = "buildagent"
	 vb.cpus = 2
   end
   buildagent.vm.provision "shell", inline: <<-SHELL
   #DockerInstall
     sudo apt-get update
   sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release -y
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
   echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
   sudo apt-get update
   sudo apt-get install docker-ce docker-ce-cli containerd.io -y
   sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
   sudo chmod +x /usr/local/bin/docker-compose
   #DockerInstall
   SHELL
  end

#k8smaster
  config.vm.define "k8smaster" do |k8smaster|
    k8smaster.vm.box = "ubuntu/focal64"
	config.vm.box_download_insecure=true
	config.vm.boot_timeout
    config.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller"
	k8smaster.vm.provider "virtualbox" do |vb|
     vb.memory = "3000"
	 vb.cpus = 2
   end
   k8smaster.vm.provision "shell", inline: <<-SHELL
   sudo apt-get update
  
   
   SHELL
  end
#k8sworker
  config.vm.define "k8sworker" do |k8sworker|
    k8sworker.vm.box = "ubuntu/focal64"
	config.vm.box_download_insecure=true
	config.vm.boot_timeout
    config.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller"
	k8sworker.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
	 vb.cpus = 2
   end
   k8sworker.vm.provision "shell", inline: <<-SHELL
   sudo apt-get update
  
   
   SHELL
  end
 
end